@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package nowebsite.makertechno.the_trackers.core.track.algorithm;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;